spring.application.name=plantillas
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://mysql-3ccc57bb-fifa.b.aivencloud.com:28538/defaultdb?useSSL=true&requireSSL=true

spring.datasource.username=avnadmin
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
